### ISSUE TITLE
Does this works as a subcomponent?

### ISSUE THREAD

**Issue by tsuharesu** [IVIanuu/Contributer#1]
I'm currently using this and it works *if* I add the module to my ApplicationComponent. I would like to use it as a Subcomponent of a Activity module (another subcomponent). Right now it compiles but at runtime I get a `Caused by: java.lang.IllegalArgumentException: No injector factory bound for Class<com.wakingup.android.home.HomeController>`. I don't know if I'm making something wrong or this does not work as a third subcomponent.

My code almost like this:
```
@AndroidInjectorKeyRegistry(keys = [ControllerKey::class])
@Singleton
@Component(modules = [
    AndroidSupportInjectionModule::class,
    ConductorInjectionModule::class,
    ApplicationModule::class,
    ActivityBindingModule::class])
interface ApplicationComponent : AndroidInjector<WakingUp> {

    @Component.Builder
    interface Builder {
        @BindsInstance
        fun application(application: Application): Builder

        fun build(): ApplicationComponent
    }
}

@Module
abstract class ActivityBindingModule {
    @ActivityScoped
    @ContributesAndroidInjector(modules = [ControllerBindingModule::class])
    abstract fun bindHomeActivity(): HomeActivity
}

@Module
abstract class ControllerBindingModule {
    @ContributesAndroidInjector
    abstract fun bindHomeController(): HomeController

    @ContributesAndroidInjector
    abstract fun bindHomeTabController(): HomeTabController

    @ContributesAndroidInjector
    abstract fun bindPodcastsTabController(): PodcastsTabController
}
```

**Comment by IVIanuu** [comment]
The module hierarchy looks good. Does your home activity implement the HasControllerInjector interface?

**Comment by tsuharesu** [comment]
My Application does. It had work, from what I saw in `ConductorInjection`.

**Comment by IVIanuu** [comment]
Your activity must implement it. Your app component does not know about the subcomponents of your activity component thats the reason that no injector was found.

**Comment by tsuharesu** [comment]
Let me try that.

**Comment by IVIanuu** [comment]
It should work. You can also add the Controllerbindingmodule to your application class but then you cannot inject activity scoped stuff into controllers

**Comment by tsuharesu** [comment]
Thanks, it worked!
